### ISSUE TITLE
其实参数不需要那么多

### ISSUE THREAD

**Issue by dfaofeng** [MiracleXYZ/bili-interactive-spoiler#2]
https://api.bilibili.com/x/stein/nodeinfo?aid=61094390&node_id=99974&graph_version=5146
只需要aid,node_id(分p的id),graph_version(互动视频的版本?)

**Comment by MiracleXYZ** [comment]
其他的参数有些是调整布局和输出格式，有些是控制访问速度避免被B站封掉IP；另外，`graphviz` 包需要手动定义中文字体，否则输出的pdf无法显示中文，所以 `fontname` 也是必要的。

**Comment by dfaofeng** [comment]
大佬.能否直接输出图片呢？？pdf文件需要丢到浏览器才能看...

**Comment by simon300000** [comment]
graphviz应该可以输出png和svg

**Comment by MiracleXYZ** [comment]
嗯，下个版本增加一个 `output_format` 参数

**Comment by MiracleXYZ** [comment]
已经更新：加入输出格式（pdf/png/svg）
